steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/kubernates-12345/pratham-repo/container2:latest", "."]
  
  # Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/kubernates-12345/pratham-repo/container2:latest"]

  # Update the deployment image in GKE
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials pratham-cluster --region us-central1
        kubectl set image deployment/container2 container2=us-central1-docker.pkg.dev/kubernates-12345/pratham-repo/container2:latest

images:
  - "us-central1-docker.pkg.dev/kubernates-12345/pratham-repo/container2:latest"

options:
  logging: CLOUD_LOGGING_ONLY