steps:
  # Build the Docker image for Container 2
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "us-central1-docker.pkg.dev/kubernates-12345/pratham-repo/container2:latest", "."]
  
  # Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/kubernates-12345/pratham-repo/container2:latest"]

  # Deploy Container 2 to GKE
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials pratham-cluster --region us-central1
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

# Specify the images built and pushed
images:
  - "us-central1-docker.pkg.dev/kubernates-12345/pratham-repo/container2:latest"

# Set logging to Cloud Logging only
options:
  logging: CLOUD_LOGGING_ONLY


# test 1