apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: gcr.io/kubernates-12345/container2:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /pratham_PV_dir
              name: pratham-volume
      volumes:
        - name: pratham-volume
          persistentVolumeClaim:
            claimName: pratham-pvc